# level 81:
# 1) ```py
# def print_numbers():

#     for კესანე in range(5):
#         print("ახალი ხაზი")
#         print(კესანე)
#         print("ხაზი დასრულდა")
# print_numbers()
# ```
# ფუქნცია განაახლეთ და გადაეხით მას პარამეტრი და როცა ფუქნციას გადაცემთ არგუმენტებს იმდენჯერ დაგვიპრინტოს ეგ ციფრი for loop ში
def print_numbers(გოა):

    for kesane in range(გოა):
         print("ახალი ხაზი")
         print(kesane)
         print("ხაზი დასრულდა")
print_numbers(4)
print_numbers(5)
print_numbers(31)
print_numbers(65427)
print_numbers(27)
print_numbers(42)
print_numbers(43)
print_numbers(412)
print_numbers(412)
print_numbers(4)
print_numbers(865)
print_numbers(4)
print_numbers(4)
print_numbers(4)
print_numbers(4)
print_numbers(4)
print_numbers(4)
print_numbers(4)
print_numbers(4)
print_numbers(4)
print_numbers(4541)
print_numbers(42)
print_numbers(434)
print_numbers(442)
print_numbers(436)
print_numbers(643)
print_numbers(5134)
print_numbers(413)
print_numbers(465)
print_numbers(9876)
print_numbers(436)
print_numbers(424)
print_numbers(423)
print_numbers6(55)
print_numbers(42366666666666666666666666)
print_numbers(42)
print_numbers(434)
print_numbers(5143)
print_numbers(4)